---
apiVersion: v1
kind: Pod
metadata:
  name: webserver-pod
  labels:
    environment: production
    release: stable
spec:
  containers:
    - command: ["sleep", "3600"]
      image: busybox
      name: busybox-container
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
