---
apiVersion: v1
kind: Pod
metadata:
  name: webserver-pod
  labels:
    app: liveness-http-busybox
spec:
  containers:
    - command: ["sleep", "3600"]
      image: busybox
      name: busybox-container
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 15
        timeoutSeconds: 1
      
